name: Eksys
description: "Eksys app by EAHM."
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter_local_notifications: ^19.4.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  # geolocator: ^12.0.0
  go_router: ^14.3.0
  # intl: ^0.20.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8

  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  image_picker: ^1.0.4
  font_awesome_flutter: ^10.8.0
  syncfusion_flutter_charts: ^26.2.14
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.4
  flutter_bootstrap: "^2.0.0"
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.0
  carousel_slider: ^5.0.0

  http: ^1.2.0
  file_picker: ^8.0.0
  pocketbase: ^0.23.0+1
  cached_network_image: ^3.4.1
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  saver_gallery: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icon/

flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "assets/images/ic_launcher_2.png" # logo transparan kamu
  background_color: "#00302F" # warna background icon
  adaptive_icon_background: "#00302F"
  adaptive_icon_foreground: "assets/images/ic_launcher_2.png"
